### ISSUE TITLE
On Fedora 31 does not work or extended guide

### ISSUE THREAD

**Issue by xzj8b3** [rek7/ddoor#1]
cd /home/xzj8b3/test/ddor
bash: cd: /home/xzj8b3/test/ddor:file o directory inesistente ?????

What's the matter?

**Comment by rek7** [comment]
Can you please provide more information, did you also run the compile.sh script in the same directory that the repo was cloned in?

**Comment by xzj8b3** [comment]
> Can you please provide more information, did you also run the compile.sh script in the same directory that the repo was cloned in?

I just re-installed for a problem, as soon as I try again I'll tell you .... you could send me exact commands to install it, I had cloned repo but I think you could not install it and I would have liked to testar

**Comment by rek7** [comment]
ok so you just clone the repo and go into the directory and run "sh compile.sh"
